FROM python:3.6-alpine

WORKDIR /usr/src/app

ENV FILE \
    COUNT \
    MODEL \
    API_HOST="frontend:8080" \
    BACKOFF="5" \
    PREPROCESS="none" \
    POSTPROCESS="none" \
    UPLOAD_PREFIX="uploads" \
    RETRY_COUNT="3" \
    RETRY_BACKOFF="1" \
    EXPIRE_TIME="3600"

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENTRYPOINT ["./bin/entrypoint.sh"]
